services:
  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tukubuku_php
    restart: unless-stopped
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - tukubuku-net
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "8081:8081"

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: tukubuku_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - tukubuku-net
    deploy:
      resources:
        limits:
          memory: 128M

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: tukubuku_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - tukubuku-net
    deploy:
      resources:
        limits:
          memory: 1536M

  # Redis Service
  redis:
    image: redis:alpine
    container_name: tukubuku_redis
    restart: unless-stopped
    command: [ "redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru" ]
    networks:
      - tukubuku-net
    deploy:
      resources:
        limits:
          memory: 640M

networks:
  tukubuku-net:
    driver: bridge

volumes:
  mysql_data:
